CREATE DATABASE IF NOT EXISTS BrockDb;

USE BrockDb;

DELIMITER ;;

CREATE TABLE Course(
    CrsCode VARCHAR(255) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CrsName VARCHAR(255) NOT NULL,
    CrsDesc TEXT(65535),
    DeliveryMethod VARCHAR(255) NOT NULL,
    CrsLocation VARCHAR(255) NOT NULL,
    CrsTiming DATETIME,
    CrsDays VARCHAR(255),
    CrsDuration VARCHAR(255) NOT NULL,
    CrsInstructor VARCHAR(255) NOT NULL
);

CREATE TABLE PreRequisites(
    PrereqID VARCHAR(255) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CrsCode VARCHAR(255) NOT NULL,
    PrereqCode VARCHAR(255) NOT NULL
);

CREATE TABLE Exam(
    ExamID VARCHAR(255) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CrsCode VARCHAR(255) NOT NULL,
    ExamLocation VARCHAR(255) NOT NULL,
    ExamDateTime VARCHAR(255) NOT NULL,
    ExamDelivery VARCHAR(255) NOT NULL
);

CREATE TABLE Department(
    DeptID VARCHAR(255) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DeptName VARCHAR(255) NOT NULL,
    DeptPrefix VARCHAR(255) NOT NULL,
    DeptLink VARCHAR(255) NOT NULL,
    DeptChair VARCHAR(255) NOT NULL,
    ParentFac VARCHAR(255) NOT NULL
);

CREATE TABLE Staff(
    StaffID VARCHAR(255) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FullName VARCHAR(255) NOT NULL,
    StaffEmail VARCHAR(255) NOT NULL,
    StaffPhone VARCHAR(255) NOT NULL,
    StaffRole VARCHAR(255) NOT NULL,
    StaffDept VARCHAR(255) NOT NULL
);

CREATE TABLE Faculty(
    FacID VARCHAR(255) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FacName VARCHAR(255) NOT NULL,
    FacDesc VARCHAR(255) NOT NULL,
    FacLink VARCHAR(255) NOT NULL,
    FacEmail VARCHAR(255) NOT NULL
);

CREATE TABLE Program(
    PrgID VARCHAR(255) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PrgName VARCHAR(255) NOT NULL,
    PrgDesc VARCHAR(255) NOT NULL,
    PrgLink VARCHAR(255) NOT NULL,
    PrgReqs VARCHAR(255) NOT NULL,
    PrgFac VARCHAR(255) NOT NULL
);

